### PR TITLE
gdformat: find GDScript files recursively in a directory

### LINKED ISSUE #75: Allow recursively formatting files
Instead of `gdformat file.gd`, I would like to do this for all GDScript files at once. It would be nice to have a recursive option, something like `gdformat -R` which would recursively format all files in the current working directory.

### PR DESCRIPTION
**Pull request by NathanLovato**
Closes #75 

Before testing the code, I'd like to know if the approach matches your expectations. If only passing a directory as an argument, the program will recursively find .gd files in it and pass them to gdformat.

Other options:

- Do that for every directory passed as an argument. For example, `gdformat src/Autoload src/Main test.gd` would recursively find .gd files in two directories and format test.gd.
- Same as above, but have an explicit `--recursive` option. Passing a directory would find files in that directory non-recursively unless the option is provided.

### CODE REVIEW

**Comment by NathanLovato** [comment]
@aaronfranke @Scony I'd like your thoughts on that. It's an easy feature to code, it's just that we have to figure out the design. 

On Linux, normally, any program that can modify or move files has an explicit --recursive option and prevents you from operating on directories without that.

That's in part because files and directories can have the same names, and from the shell you may access them the same way:

For example, `rm .test` could attempt to remove a hidden file named ".test" or a directory named ".test". In the latter case, you must specify the `-r/--recursive` option.

**Comment by aaronfranke** [comment]
Either seems fine to me. For this tool, an explicit recursive flag seems a bit unnecessary, since it only works on GDScript files, and I very seriously doubt you'd have a directory ending in `.gd`. But also, it would be fine if the flag was explicit (if so, the single-letter version should be a capital R: `-R`).

**Comment by NathanLovato** [comment]
I'm saying -r because on all linux/cygwin base tools, it's -r / --recursive. Might be different on Windows or other tools.

I'm fine without the option flag, we can check for directories vs files.

And so, should the tool probe each directory passed as an argument?

**Comment by aaronfranke** [comment]
Many if not most Linux tools support `-R` (`rm`) if not use it exclusively (`chmod`, `chown`) or as the preferred option (`cp`, `grep`). I actually can't find any common commands  that only support `-r`. `chmod` has to have `-R` because `-r` means "remove read permissions".

**Comment by NathanLovato** [comment]
It's not a discussion or a pointless, and I trust you. I genuinely thought -r was common, it's the way I write it when I use it. There are so many options with shell programs it's hard to know them all, even using the shell all day.

**Comment by NathanLovato** [comment]
Just tested it with some directories and paths, it seems to be working.

**Pull request merged**
