### PR TITLE
Serialize and cache the parser on the disk

### LINKED ISSUE #61: Improve startup speed by caching the lark trees to disk
I got started on that already, using python's pickle module to write the parser objects as binary after computing them for the first time.

It's a bit crude right now but startup is near-instant from the second run of gdformat onwards here, with an SSD drive.

I just need to figure out where to save the cache files depending of the OS, any suggestion for that? On unix it's $HOME/.cache, but how about windows?

```py
    @cached_property
    def _parser_with_metadata(self) -> Tree:
        tree: Tree = None
        filename: str = "parser_with_metadata"
        filepath: str = os.path.join(self._cache_dirpath, filename)
        if os.path.exists(filepath):
            tree = self.load(filepath)
            print("loaded tree object {}".format(tree))
        else:
            tree = Lark.open(
                os.path.join(self._directory, "gdscript.lark"),
                postlex=Indenter(),
                parser="lalr",
                start="start",
                propagate_positions=True,
                maybe_placeholders=False,
            )
            self.save(tree, filename)
        return tree


    def save(self, parser: Tree, filename: str) -> None:
        """Serializes the Lark parser and saves it to the disk."""
        if not os.path.exists(self._cache_dirpath):
            os.makedirs(self._cache_dirpath)
        path: str = os.path.join(self._cache_dirpath, filename)
        print("Saving to path {}".format(path))
        pickle.dump(parser, open(path, "wb"), protocol=4)

    def load(self, filename: str) -> Tree:
        """Loads the Lark parser from the disk and deserializes it."""
        path: str = os.path.join(self._cache_dirpath, filename)
        print("Loading from {}".format(path))
        return pickle.load(open(path, "rb"))
```

### PR DESCRIPTION
**Pull request by NathanLovato**
Closes #61

### CODE REVIEW

**Comment by NathanLovato** [comment]
Mh this direction might be a mistake. I've made a minimal example to test the bottleneck and caching here. Generating a parser object takes ~.5 s to evaluate on average here. Maybe the bottleneck is elsewhere in the program, a mix of using several parsers and/or parsing initially?

**Comment by NathanLovato** [comment]
Thanks to lark's... maintainer I believe? This now works, using pickle. In the latest lark master, you now have save and load methods on the Lark class. But until we can use it, I've added similar code.

The process startup gain here is of 40-45%, making gdformat run on a single buffer in about .4 seconds instead of .7. Running gdformat on many files at once suggests that the actual parsing and formatting make up quite a bit of these .4 seconds. But that's already a good start for 

The commit currently breaks some tests so it's not ready to land yet - I probably broke the comments parser refactoring. Also, I don't have windows-specific code yet for the cache storage location.

But could you tell me if you're fine with the approach?

**Comment by Scony** [comment]
Yeah, I've exchanged a couple of emails with him, so he probably has seen our discussions and intervened :) Anyway, I think your approach is very well. In the past, during benchmarking I've found that ~95% time is spent on loading grammar. I'll check how does it look like after your changes. Maybe it will be possible to improve a little bit more.

**Comment by Scony** [comment]
So, looks like we still need to pickle `_loosen_parser_with_metada` which is used for safety checks.
x

**Comment by Scony** [comment]
Okay, I've fixed caching of  `_loosen_parser_with_metada` and fixed doubled comment parsing and now it's much better. We're spending ~70% of the time in parsing and 27% on loading. We're parsing 8 times:
 - (2) basic parsing: actual code parsing + comments parsing
 - (2) the same again but for formatted code (stability check)
 - (2) tree invariant check: actual code parsing + formatted code parsing (both using loosen grammar)
 - (2) comments persistence check: actual code comments parsing + formatted code comments parsing
Clearly (with some refactoring) we can avoid 2x comments parsing. Also, I have an idea of how to avoid using loosen grammar. But anyway, ATM. it's all not that bad:
w_safety_checks

**Comment by NathanLovato** [comment]
I just pushed two new commits to round out the features. Now it's still breaking some tests where it's like I changed the parsers. But I can't see where I've modified them. Any idea?

**Comment by Scony** [comment]
I cannot tell by code inspection, so I'll download it and check (on Saturday as today I'm AFK).

**Comment by Scony** [comment]
Okay, I've merged your changes to another branch and applied the fix (you missed `is_loosened_parser=True` in invocation). I'll get rid of the loosened parser, disable file cache from tests and test it all together on Linux and windows. Once everything is fine, I'll merge to master ;) If you have anything to add, raise PR to branch.

**Comment by NathanLovato** [comment]
Thanks :)

**Pull request closed without merging**
